from pathlib import Path
from unittest import TestCase


ROOT = Path(__file__).resolve().parents[1]


class InstalledUiDocumentationTests(TestCase):
    def test_installed_ui_contract_is_published(self):
        readme = (ROOT / "README.md").read_text(encoding="utf-8")
        docs = (ROOT / "docs" / "installed-ui.md").read_text(encoding="utf-8")
        guide = (ROOT / "docs" / "README.md").read_text(encoding="utf-8")
        pyproject = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
        roadmap = (ROOT / "ROADMAP.md").read_text(encoding="utf-8")

        self.assertIn("skill2workflow ui --port 4173", readme)
        self.assertIn("docs/installed-ui.md", readme)
        self.assertIn("loopback-only", docs)
        self.assertIn("does not read runtime state", docs)
        self.assertIn("--service-url", docs)
        self.assertIn("--auth-token-file", docs)
        self.assertIn("Load Live Snapshot", docs)
        self.assertIn("same-origin `/api/v1/control-snapshot`", docs)
        self.assertIn("/api/v1/service-probe", docs)
        self.assertIn("static mode", docs)
        self.assertIn("not ready", docs)
        self.assertIn("Download Support Bundle", docs)
        self.assertIn("/api/v1/support-bundle", docs)
        self.assertIn("Load Live Schedules", docs)
        self.assertIn("/api/v1/recurring-schedules", docs)
        self.assertIn("skill2workflow-recurring-schedule-list-0.1.0", docs)
        self.assertIn("Load Live Readiness", docs)
        self.assertIn("/api/v1/operational-readiness", docs)
        self.assertIn("skill2workflow-operational-readiness-0.1.0", docs)
        self.assertIn("Load Live Workflows", docs)
        self.assertIn("/api/v1/workflows", docs)
        self.assertIn("skill2workflow-workflow-inventory-0.1.0", docs)
        self.assertIn("Review Workflow Plan", docs)
        self.assertIn("/api/v1/workflow-explanations/{workflow_id}/{version}", docs)
        self.assertIn("skill2workflow-workflow-explanation-0.1.0", docs)
        self.assertIn("Check Empty Trigger", docs)
        self.assertIn("/api/v1/workflow-preflights/{workflow_id}/{version}", docs)
        self.assertIn("skill2workflow-workflow-preflight-0.1.0", docs)
        self.assertIn("Compare Versions", docs)
        self.assertIn("/api/v1/workflow-diffs/{workflow_id}/{from_version}/{to_version}", docs)
        self.assertIn("skill2workflow-workflow-diff-0.1.0", docs)
        self.assertIn("Load Dispatch Evidence", docs)
        self.assertIn("recurring-schedule-dispatch-pages/{schedule_id}", docs)
        self.assertIn("Load Older Dispatches", docs)
        self.assertIn("skill2workflow-recurring-schedule-dispatch-page-0.1.0", docs)
        self.assertIn("Record Review", docs)
        self.assertIn("recurring-schedule-dispatch-reviews/{dispatch_id}", docs)
        self.assertIn("Promote to production", docs)
        self.assertIn("/api/v1/workflow-promotions", docs)
        self.assertIn("Installed UI", guide)
        self.assertIn('"share/skill2workflow/web"', pyproject)
        self.assertIn("Loop 206: Installed Static UI Launcher", roadmap)
        self.assertIn("Loop 207: Authenticated Live Control-Plane UI", roadmap)
        self.assertIn("Loop 208: Live Service Readiness Badge", roadmap)
        self.assertIn("Loop 209: Bounded Live Snapshot Refresh", roadmap)
        self.assertIn("Loop 210: Protected Live Support-Bundle Download", roadmap)
        self.assertIn("Loop 211: Confirmation-Protected Live Human-Gate Action", roadmap)
        self.assertIn("Loop 212: Bounded Live Run-Detail Evidence", roadmap)
        self.assertIn("Loop 213: Bounded Live Run Discovery", roadmap)
        self.assertIn("Loop 214: Confirmation-Protected Live Cooperative Cancellation", roadmap)
        self.assertIn("Loop 215: Bounded Live Audit Discovery", roadmap)
        self.assertIn("Loop 216: Bounded Live Recurring-Schedule Discovery", roadmap)
        self.assertIn("Loop 217: Live Production-Readiness Diagnostics", roadmap)
        self.assertIn("Loop 218: Live Published-Workflow Inventory", roadmap)
        self.assertIn("Loop 219: Live Workflow-Plan Review", roadmap)
        self.assertIn("Loop 220: Live Empty-Trigger Preflight", roadmap)
        self.assertIn("Loop 221: Live Workflow Version Diff Review", roadmap)
        self.assertIn("Loop 222: Live Recurring-Dispatch Evidence", roadmap)
        self.assertIn("Loop 223: Live Uncertain-Dispatch Review", roadmap)
        self.assertIn("Loop 224: Live Workflow Promotion", roadmap)
