from pathlib import Path
from unittest import TestCase


ROOT = Path(__file__).resolve().parents[1]


class ControlUiContractTests(TestCase):
    def test_operator_ui_surfaces_complete_bounded_and_truncated_scope(self):
        html = (ROOT / "web" / "control.html").read_text(encoding="utf-8")
        javascript = (ROOT / "web" / "control.js").read_text(encoding="utf-8")
        css = (ROOT / "web" / "control.css").read_text(encoding="utf-8")

        self.assertIn('id="snapshot-scope"', html)
        self.assertIn('id="service-status"', html)
        self.assertIn('id="toggle-refresh"', html)
        self.assertIn('aria-pressed="false"', html)
        self.assertIn('id="download-bundle"', html)
        self.assertIn('id="load-live"', html)
        self.assertIn('aria-live="polite"', html)
        self.assertIn("validateSnapshotWindow", javascript)
        self.assertIn("renderSnapshotScope", javascript)
        self.assertIn("Complete offline snapshot", javascript)
        self.assertIn("Bounded snapshot", javascript)
        self.assertIn("collection is truncated", javascript)
        self.assertIn("/api/v1/control-snapshot", javascript)
        self.assertIn("loadLiveSnapshot", javascript)
        self.assertIn("/api/v1/service-probe", javascript)
        self.assertIn("validateServiceProbe", javascript)
        self.assertIn("Live service: ready", javascript)
        self.assertIn("AUTO_REFRESH_INTERVAL_MS = 10000", javascript)
        self.assertIn("toggleAutoRefresh", javascript)
        self.assertIn("visibilitychange", javascript)
        self.assertIn("Last refresh failed; showing the previous snapshot.", javascript)
        self.assertIn("/api/v1/support-bundle", javascript)
        self.assertIn("downloadSupportBundle", javascript)
        self.assertIn("skill2workflow-support-bundle.json", javascript)
        self.assertIn("Download Support Bundle", html)
        self.assertIn('id="human-gate-actions"', html)
        self.assertIn('id="approve-run"', html)
        self.assertIn('id="reject-run"', html)
        self.assertIn("decideSelectedRun", javascript)
        self.assertIn("selectedWaitingRun", javascript)
        self.assertIn("/api/v1/runs/", javascript)
        self.assertIn('method: "POST"', javascript)
        self.assertIn("window.confirm", javascript)
        self.assertIn('id="run-cancel-actions"', html)
        self.assertIn('id="cancel-run"', html)
        self.assertIn("cancelSelectedRun", javascript)
        self.assertIn("selectedCancellableRun", javascript)
        self.assertIn("/cancel", javascript)
        self.assertIn('body: "{}"', javascript)
        self.assertIn("Cancellation is cooperative", javascript)
        self.assertIn("loadLiveRunDetail", javascript)
        self.assertIn("validateLiveRunDetail", javascript)
        self.assertIn("skill2workflow-run-detail-0.1.0", javascript)
        self.assertIn("isLiveSnapshot", javascript)
        self.assertIn('id="run-detail-status"', html)
        self.assertIn("Redacted event tail loaded", javascript)
        self.assertIn('id="load-older-runs"', html)
        self.assertIn("Load Older Runs", html)
        self.assertIn("/api/v1/run-page", javascript)
        self.assertIn("loadOlderRuns", javascript)
        self.assertIn("validateLiveRunPage", javascript)
        self.assertIn("RUN_PAGE_SCHEMA", javascript)
        self.assertIn("LIVE_RUN_ROWS_MAX = 500", javascript)
        self.assertIn('id="load-older-audit"', html)
        self.assertIn("Load Older Audit", html)
        self.assertIn("/api/v1/audit-page", javascript)
        self.assertIn("loadOlderAudit", javascript)
        self.assertIn("validateLiveAuditPage", javascript)
        self.assertIn("AUDIT_PAGE_SCHEMA", javascript)
        self.assertIn("LIVE_AUDIT_ROWS_MAX = 500", javascript)
        self.assertIn('id="load-live-schedules"', html)
        self.assertIn("Load Live Schedules", html)
        self.assertIn("/api/v1/recurring-schedules", javascript)
        self.assertIn("loadLiveSchedules", javascript)
        self.assertIn("validateLiveScheduleList", javascript)
        self.assertIn("SCHEDULE_LIST_SCHEMA", javascript)
        self.assertIn('data-view="schedules"', html)
        self.assertIn('id="schedule-rows"', html)
        self.assertIn('id="schedule-page-status"', html)
        self.assertIn('id="load-live-readiness"', html)
        self.assertIn("Load Live Readiness", html)
        self.assertIn("/api/v1/operational-readiness", javascript)
        self.assertIn("loadLiveReadiness", javascript)
        self.assertIn("validateOperationalReadiness", javascript)
        self.assertIn("OPERATIONAL_READINESS_SCHEMA", javascript)
        self.assertIn('data-view="readiness"', html)
        self.assertIn('id="readiness-rows"', html)
        self.assertIn('id="readiness-page-status"', html)
        self.assertIn(".snapshot-scope.is-bounded", css)
        self.assertIn(".snapshot-scope.is-truncated", css)
        self.assertIn(".service-status.is-valid", css)
        self.assertIn(".human-gate-actions", css)
        self.assertIn(".run-detail-status", css)
        self.assertIn(".run-page-status", css)
        self.assertIn(".audit-page-status", css)
        self.assertIn(".schedule-page-status", css)
        self.assertIn(".readiness-page-status", css)
        self.assertIn('id="load-live-workflows"', html)
        self.assertIn("Load Live Workflows", html)
        self.assertIn("/api/v1/workflows", javascript)
        self.assertIn("loadLiveWorkflows", javascript)
        self.assertIn("validateWorkflowInventory", javascript)
        self.assertIn("WORKFLOW_INVENTORY_SCHEMA", javascript)
        self.assertIn('data-view="live-workflows"', html)
        self.assertIn('id="live-workflow-rows"', html)
        self.assertIn('id="workflow-page-status"', html)
        self.assertIn(".workflow-page-status", css)
        self.assertIn('id="workflow-explanation-actions"', html)
        self.assertIn('id="load-workflow-explanation"', html)
        self.assertIn("Review Workflow Plan", html)
        self.assertIn("/api/v1/workflow-explanations/", javascript)
        self.assertIn("loadLiveWorkflowExplanation", javascript)
        self.assertIn("validateWorkflowExplanation", javascript)
        self.assertIn("WORKFLOW_EXPLANATION_SCHEMA", javascript)
        self.assertIn("side_effect_free", javascript)
        self.assertIn(".workflow-explanation-actions", css)
        self.assertIn('id="load-workflow-preflight"', html)
        self.assertIn("Check Empty Trigger", html)
        self.assertIn("/api/v1/workflow-preflights/", javascript)
        self.assertIn("loadLiveWorkflowPreflight", javascript)
        self.assertIn("validateWorkflowPreflight", javascript)
        self.assertIn("WORKFLOW_PREFLIGHT_SCHEMA", javascript)
        self.assertIn("empty JSON object", javascript)
        self.assertIn('id="workflow-release-file"', html)
        self.assertIn('id="publish-workflow"', html)
        self.assertIn("Stage Workflow", html)
        self.assertIn("Publish Staged Workflow", html)
        self.assertIn("/api/v1/workflow-releases", javascript)
        self.assertIn("stageWorkflowReleaseFile", javascript)
        self.assertIn("publishStagedWorkflow", javascript)
        self.assertIn("validateWorkflowRelease", javascript)
        self.assertIn("WORKFLOW_RELEASE_SCHEMA", javascript)
        self.assertIn("MAX_WORKFLOW_RELEASE_BYTES", javascript)
        self.assertIn("does not promote an alias or execute", javascript)
        self.assertIn(".file-action.is-disabled", css)
        self.assertIn('id="workflow-diff-target"', html)
        self.assertIn('id="load-workflow-diff"', html)
        self.assertIn("Compare Versions", html)
        self.assertIn("/api/v1/workflow-diffs/", javascript)
        self.assertIn("loadLiveWorkflowDiff", javascript)
        self.assertIn("validateWorkflowDiff", javascript)
        self.assertIn("WORKFLOW_DIFF_SCHEMA", javascript)
        self.assertIn(".workflow-diff-controls", css)
        self.assertIn('id="schedule-dispatch-actions"', html)
        self.assertIn('id="load-schedule-dispatches"', html)
        self.assertIn('id="load-older-schedule-dispatches"', html)
        self.assertIn("/api/v1/recurring-schedule-dispatch-pages/", javascript)
        self.assertIn("loadLiveScheduleDispatches", javascript)
        self.assertIn("validateRecurringScheduleDispatchPage", javascript)
        self.assertIn("SCHEDULE_DISPATCH_PAGE_SCHEMA", javascript)
        self.assertIn(".schedule-dispatch-actions", css)
        self.assertIn('id="schedule-dispatch-review-target"', html)
        self.assertIn('id="schedule-dispatch-review-outcome"', html)
        self.assertIn('id="review-schedule-dispatch"', html)
        self.assertIn("/api/v1/recurring-schedule-dispatch-reviews/", javascript)
        self.assertIn("reviewLiveScheduleDispatch", javascript)
        self.assertIn("validateRecurringScheduleDispatchReview", javascript)
        self.assertIn("SCHEDULE_DISPATCH_REVIEW_SCHEMA", javascript)
        self.assertIn(".run-cancel-actions", css)
        self.assertIn('id="promote-workflow"', html)
        self.assertIn("Promote to production", html)
        self.assertIn("/api/v1/workflow-promotions", javascript)
        self.assertIn("promoteLiveWorkflow", javascript)
        self.assertIn("validateWorkflowPromotion", javascript)
        self.assertIn("WORKFLOW_PROMOTION_SCHEMA", javascript)
        self.assertIn("expectedCurrentVersion", javascript)
        self.assertIn(".workflow-promotion-controls", css)
        self.assertIn('id="deprecate-workflow"', html)
        self.assertIn("Deprecate version", html)
        self.assertIn("/api/v1/workflow-deprecations", javascript)
        self.assertIn("deprecateLiveWorkflow", javascript)
        self.assertIn("validateWorkflowDeprecation", javascript)
        self.assertIn("WORKFLOW_DEPRECATION_SCHEMA", javascript)
        self.assertIn("expectedChecksum", javascript)
        self.assertIn(".workflow-deprecation-controls", css)

    def test_live_snapshot_guide_warns_ui_users_about_window_scope(self):
        guide = (ROOT / "docs" / "live-control-snapshot.md").read_text(
            encoding="utf-8"
        )

        self.assertIn("Operator UI", guide)
        self.assertIn("truncated collections", guide)
