from pathlib import Path
from unittest import TestCase


ROOT = Path(__file__).resolve().parents[1]


class ServiceDocumentationTests(TestCase):
    def test_service_guide_documents_config_lifecycle_and_security_boundary(self):
        guide = (ROOT / "docs" / "service.md").read_text(encoding="utf-8")

        self.assertIn("skill2workflow-service-0.2.0", guide)
        self.assertIn("skill2workflow service --config", guide)
        self.assertIn("GET /healthz", guide)
        self.assertIn("GET /readyz", guide)
        self.assertIn("SIGTERM", guide)
        self.assertIn("SQLite", guide)
        self.assertIn("loopback", guide)
        self.assertIn("Bearer authentication", guide)
        self.assertIn("MAX_CONCURRENT_BUSINESS_REQUESTS", guide)
        self.assertIn("Retry-After: 1", guide)
        self.assertIn("service concurrency limit reached", guide)
        self.assertIn("service_boundary_smoke.py", guide)
        self.assertIn("GET /api/v1/recurring-schedules", guide)
        self.assertIn("GET /api/v1/workflow-artifacts", guide)
        self.assertIn("GET /api/v1/backup-readiness", guide)
        self.assertIn("POST /api/v1/retention-readiness", guide)
        self.assertIn("GET /api/v1/operational-readiness", guide)
        self.assertIn("GET /api/v1/audit-integrity", guide)
        self.assertIn("GET /api/v1/runtime-info", guide)
        self.assertIn("service-trigger", guide)
        self.assertIn("remote-workflow-artifacts.md", guide)
        self.assertIn("remote-backup-readiness.md", guide)
        self.assertIn("remote-audit-integrity.md", guide)
        self.assertIn("remote-runtime-info.md", guide)
        self.assertIn("remote-trigger.md", guide)
        self.assertIn("remote-schedule-inventory.md", guide)
        self.assertIn("POST /api/v1/workflow-releases", guide)
        self.assertIn("remote-workflow-release.md", guide)
        self.assertIn("service-workflow-publish", guide)
        self.assertIn("POST /api/v1/workflow-promotions", guide)
        self.assertIn("remote-workflow-promotion.md", guide)
        self.assertIn("service-workflow-promote", guide)
        self.assertIn("POST /api/v1/workflow-deprecations", guide)
        self.assertIn("remote-workflow-deprecation.md", guide)
        self.assertIn("service-workflow-deprecate", guide)
        self.assertIn("GET /api/v1/workflow-diffs", guide)
        self.assertIn("remote-workflow-diff.md", guide)
        self.assertIn("service-workflow-diff", guide)
        self.assertIn("service-token-rotation.md", guide)
        self.assertIn("service-token-rotate", guide)
        self.assertIn("GET /api/v1/workflows", guide)
        self.assertIn("remote-workflow-inventory.md", guide)
        self.assertIn("service-workflows", guide)
        self.assertIn("remote-retention-readiness.md", guide)
        self.assertIn("service-retention-readiness", guide)
        self.assertIn("remote-operational-readiness.md", guide)
        self.assertIn("service-operational-readiness", guide)
        self.assertIn("REQUEST_SOCKET_TIMEOUT_SECONDS", guide)
        self.assertIn("HTTP `408`", guide)
        self.assertIn("request timed out", guide)
        stability = (ROOT / "docs" / "stability.md").read_text(encoding="utf-8")
        self.assertIn("five-second request-body socket deadline", stability)

    def test_readme_points_to_service_entry_point_and_completed_beta_gate(self):
        readme = (ROOT / "README.md").read_text(encoding="utf-8")

        self.assertIn("Delivery Loops 1-94 are complete", readme)
        self.assertIn("docs/service.md", readme)
        self.assertIn("Current maturity: Self-hosted Beta", readme)
